version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: driver_form_web
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
